[package]
name = "tui-tree-widget"
version = "0.1.0"
authors = ["EdJoPaTo <tui-tree-widget-cargo-package@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-width = "0.1"

[dependencies.tui]
version = "0.12"
default-features = false

[dev-dependencies]
termion = "1.5"

[dev-dependencies.tui]
version = "0.12"
default-features = false
features = ["termion"]
